# =============================================================================
# Grafana — Zipkin 数据源配置（链路追踪）
# =============================================================================
apiVersion: 1

datasources:
  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    editable: false
